//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuddyControlPanel.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BCPGlobalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BCPGlobalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuddyControlPanel.Resources.Localization.BCPGlobalization", typeof(BCPGlobalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to nearest Innkeep &amp; Exit game.
        /// </summary>
        internal static string BotAction_MoveToInnkeepAndExitGame_Label {
            get {
                return ResourceManager.GetString("BotAction_MoveToInnkeepAndExitGame_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to nearest Innkeep &amp; Logout.
        /// </summary>
        internal static string BotAction_MoveToInnkeepAndLogout_Label {
            get {
                return ResourceManager.GetString("BotAction_MoveToInnkeepAndLogout_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to nearest Innkeep &amp; Stop bot.
        /// </summary>
        internal static string BotAction_MoveToInnkeepAndStopBot_Label {
            get {
                return ResourceManager.GetString("BotAction_MoveToInnkeepAndStopBot_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorbuddy.
        /// </summary>
        internal static string BuddyBotName {
            get {
                return ResourceManager.GetString("BuddyBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click mouse to minimize or restore {0}..
        /// </summary>
        internal static string Button_BuddyPopUpDown_ToolTipFormat {
            get {
                return ResourceManager.GetString("Button_BuddyPopUpDown_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Profile Settings.
        /// </summary>
        internal static string Button_OverrideProfileSettings_Label {
            get {
                return ResourceManager.GetString("Button_OverrideProfileSettings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, these configuration settings will override those defined in the profile..
        /// </summary>
        internal static string Button_OverrideProfileSettings_ToolTip {
            get {
                return ResourceManager.GetString("Button_OverrideProfileSettings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Button_Pause_Label {
            get {
                return ResourceManager.GetString("Button_Pause_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click mouse to pause or resume {0}..
        /// </summary>
        internal static string Button_Pause_ToolTipFormat {
            get {
                return ResourceManager.GetString("Button_Pause_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Button_Start_Label {
            get {
                return ResourceManager.GetString("Button_Start_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click mouse to start {0}..
        /// </summary>
        internal static string Button_Start_ToolTipFormat {
            get {
                return ResourceManager.GetString("Button_Start_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Button_Stop_Label {
            get {
                return ResourceManager.GetString("Button_Stop_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click mouse to stop {0}..
        /// </summary>
        internal static string Button_Stop_ToolTipFormat {
            get {
                return ResourceManager.GetString("Button_Stop_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonText_Cancel {
            get {
                return ResourceManager.GetString("ButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string ButtonText_Load {
            get {
                return ResourceManager.GetString("ButtonText_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonText_No {
            get {
                return ResourceManager.GetString("ButtonText_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonText_OK {
            get {
                return ResourceManager.GetString("ButtonText_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ButtonText_Reset {
            get {
                return ResourceManager.GetString("ButtonText_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        internal static string ButtonText_ResetToDefaults {
            get {
                return ResourceManager.GetString("ButtonText_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonText_Yes {
            get {
                return ResourceManager.GetString("ButtonText_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; is not a viable keybind.{0}{0}Please select another key,{0}  or add an Alt, Ctrl, or Shift modifier{0}  to the current selection..
        /// </summary>
        internal static string Dialog_FormatText_IsNotAValidKeybind {
            get {
                return ResourceManager.GetString("Dialog_FormatText_IsNotAValidKeybind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Actions.
        /// </summary>
        internal static string GeneralText_BotActions {
            get {
                return ResourceManager.GetString("GeneralText_BotActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects specific activities for this bot to conduct..
        /// </summary>
        internal static string GeneralText_BotActionsDefined_UnknownBot {
            get {
                return ResourceManager.GetString("GeneralText_BotActionsDefined_UnknownBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available actions for this bot..
        /// </summary>
        internal static string GeneralText_BotActionsNotAvailable_UnknownBot {
            get {
                return ResourceManager.GetString("GeneralText_BotActionsNotAvailable_UnknownBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon is not in an area where vendors are accessible..
        /// </summary>
        internal static string GeneralText_BotActionUnusable_VendorsInaccessible {
            get {
                return ResourceManager.GetString("GeneralText_BotActionUnusable_VendorsInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled—not a QuestBot profile..
        /// </summary>
        internal static string GeneralText_DisabledNotAQuestBotProfile {
            get {
                return ResourceManager.GetString("GeneralText_DisabledNotAQuestBotProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled while bot is running..
        /// </summary>
        internal static string GeneralText_DisabledWhileBotIsRunning {
            get {
                return ResourceManager.GetString("GeneralText_DisabledWhileBotIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled while profile is loading..
        /// </summary>
        internal static string GeneralText_DisabledWhileProfileIsLoading {
            get {
                return ResourceManager.GetString("GeneralText_DisabledWhileProfileIsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to exit {0}?.
        /// </summary>
        internal static string GeneralText_ExitConfirmationFormat {
            get {
                return ResourceManager.GetString("GeneralText_ExitConfirmationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed to start {1}.
        /// </summary>
        internal static string GeneralText_FailedToStartBot {
            get {
                return ResourceManager.GetString("GeneralText_FailedToStartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Please see log for details).
        /// </summary>
        internal static string GeneralText_FinalLogPhrase {
            get {
                return ResourceManager.GetString("GeneralText_FinalLogPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It does make sense for both Mail and Sell to be checked, simultaneously.  Mailing is given preference over selling for items that are eligible for both.  Items that cannot be mailed—perhaps because they are soulbound—will be sold instead..
        /// </summary>
        internal static string GeneralText_HowItWorks_MailSell {
            get {
                return ResourceManager.GetString("GeneralText_HowItWorks_MailSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading profile....
        /// </summary>
        internal static string GeneralText_LoadingProfile {
            get {
                return ResourceManager.GetString("GeneralText_LoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating an Innkeeper....
        /// </summary>
        internal static string GeneralText_LocatingInnkeeper {
            get {
                return ResourceManager.GetString("GeneralText_LocatingInnkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-mouse button to enable/disable..
        /// </summary>
        internal static string GeneralText_MouseLeftButtonToEnableOrDisable {
            get {
                return ResourceManager.GetString("GeneralText_MouseLeftButtonToEnableOrDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-mouse button for plugin settings..
        /// </summary>
        internal static string GeneralText_MouseRightButtonForPluginSettings {
            get {
                return ResourceManager.GetString("GeneralText_MouseRightButtonForPluginSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click mouse for context menu..
        /// </summary>
        internal static string GeneralText_MouseRightForContextMenu {
            get {
                return ResourceManager.GetString("GeneralText_MouseRightForContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string GeneralText_None {
            get {
                return ResourceManager.GetString("GeneralText_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile currently selected..
        /// </summary>
        internal static string GeneralText_NoProfileCurrentlySelected {
            get {
                return ResourceManager.GetString("GeneralText_NoProfileCurrentlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only profiles for the following bots may be configured:.
        /// </summary>
        internal static string GeneralText_OnlyProfilesForTheFollowingBotsMayBeConfigured {
            get {
                return ResourceManager.GetString("GeneralText_OnlyProfilesForTheFollowingBotsMayBeConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause hotkey ignored: {0} is not running.
        /// </summary>
        internal static string GeneralText_PauseHotkeyIgnoredBotIsNotRunning {
            get {
                return ResourceManager.GetString("GeneralText_PauseHotkeyIgnoredBotIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin has no settings.
        /// </summary>
        internal static string GeneralText_PluginHasNoSettings {
            get {
                return ResourceManager.GetString("GeneralText_PluginHasNoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin is now disabled.
        /// </summary>
        internal static string GeneralText_PluginIsNowDisabled {
            get {
                return ResourceManager.GetString("GeneralText_PluginIsNowDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin is now enabled.
        /// </summary>
        internal static string GeneralText_PluginIsNowEnabled {
            get {
                return ResourceManager.GetString("GeneralText_PluginIsNowEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem encountered trying to obtain.
        /// </summary>
        internal static string GeneralText_ProblemEncounteredTryingToObtain {
            get {
                return ResourceManager.GetString("GeneralText_ProblemEncounteredTryingToObtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile could not be found:.
        /// </summary>
        internal static string GeneralText_ProfileCouldNotBeFound {
            get {
                return ResourceManager.GetString("GeneralText_ProfileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load profile:.
        /// </summary>
        internal static string GeneralText_ProfileFailedToLoad {
            get {
                return ResourceManager.GetString("GeneralText_ProfileFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile load completed.
        /// </summary>
        internal static string GeneralText_ProfileLoadCompleted {
            get {
                return ResourceManager.GetString("GeneralText_ProfileLoadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no profile loaded to configure..
        /// </summary>
        internal static string GeneralText_ThereIsNoProfileLoadedToConfigure {
            get {
                return ResourceManager.GetString("GeneralText_ThereIsNoProfileLoadedToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error requesting the web profile:.
        /// </summary>
        internal static string GeneralText_ThereWasAnErrorRequestingTheWebProfile {
            get {
                return ResourceManager.GetString("GeneralText_ThereWasAnErrorRequestingTheWebProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is only available to the following bots:.
        /// </summary>
        internal static string GeneralText_ThisActionIsOnlyAvailableForTheFollowingBots {
            get {
                return ResourceManager.GetString("GeneralText_ThisActionIsOnlyAvailableForTheFollowingBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string GeneralText_Unknown {
            get {
                return ResourceManager.GetString("GeneralText_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User canceled Innkeeper pursuit... Game Exit aborted..
        /// </summary>
        internal static string GeneralText_UserCanceledInnkeeperGameExit {
            get {
                return ResourceManager.GetString("GeneralText_UserCanceledInnkeeperGameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User canceled Innkeeper pursuit... Logout aborted..
        /// </summary>
        internal static string GeneralText_UserCanceledInnkeeperLogout {
            get {
                return ResourceManager.GetString("GeneralText_UserCanceledInnkeeperLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived at {0}... Bot stopped..
        /// </summary>
        internal static string GeneralTextFormat_ArrivedAtLocation_BotStopped {
            get {
                return ResourceManager.GetString("GeneralTextFormat_ArrivedAtLocation_BotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived at {1}... Exiting game.{0}(To cancel, turn off &apos;Innkeeper&apos; Bot Action).
        /// </summary>
        internal static string GeneralTextFormat_ArrivedAtLocation_GameExiting {
            get {
                return ResourceManager.GetString("GeneralTextFormat_ArrivedAtLocation_GameExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived at {1}... Logging out.{0}(To cancel, turn off &apos;Innkeeper&apos; Bot Action).
        /// </summary>
        internal static string GeneralTextFormat_ArrivedAtLocation_LoggingOut {
            get {
                return ResourceManager.GetString("GeneralTextFormat_ArrivedAtLocation_LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects specific activities for the {0} bot to conduct..
        /// </summary>
        internal static string GeneralTextFormat_BotActionsDefined_SpecificBot {
            get {
                return ResourceManager.GetString("GeneralTextFormat_BotActionsDefined_SpecificBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available actions for the {0} bot..
        /// </summary>
        internal static string GeneralTextFormat_BotActionsNotAvailable_SpecificBot {
            get {
                return ResourceManager.GetString("GeneralTextFormat_BotActionsNotAvailable_SpecificBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default profile settings are in use.{0}Current profile setting is reflected here.
        /// </summary>
        internal static string GeneralTextFormat_DefaultProfileSettingInUse {
            get {
                return ResourceManager.GetString("GeneralTextFormat_DefaultProfileSettingInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paused {1}.
        /// </summary>
        internal static string GeneralTextFormat_Event_Paused {
            get {
                return ResourceManager.GetString("GeneralTextFormat_Event_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resumed {1}.
        /// </summary>
        internal static string GeneralTextFormat_Event_Resumed {
            get {
                return ResourceManager.GetString("GeneralTextFormat_Event_Resumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} running {1}.
        /// </summary>
        internal static string GeneralTextFormat_Event_Running {
            get {
                return ResourceManager.GetString("GeneralTextFormat_Event_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stopped.
        /// </summary>
        internal static string GeneralTextFormat_Event_Stopped {
            get {
                return ResourceManager.GetString("GeneralTextFormat_Event_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stopping {1}....
        /// </summary>
        internal static string GeneralTextFormat_Event_Stopping {
            get {
                return ResourceManager.GetString("GeneralTextFormat_Event_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, {1} will not try to skip ahead to a level-appropriate part of the profile when the bot is started.  This feature is useful for &apos;completionists&apos;, such as those seeking the Loremaster achievement.  Enabling this feature means you may have to occasionally help {1} if you are considerably over-geared or over-level..
        /// </summary>
        internal static string GeneralTextFormat_HowItWorks_IgnoreCheckpoints {
            get {
                return ResourceManager.GetString("GeneralTextFormat_HowItWorks_IgnoreCheckpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile setting overrides are maintained on a per-toon basis.{0}If &apos;Override Profile Settings&apos; is enabled, the changes affect all profiles..
        /// </summary>
        internal static string GeneralTextFormat_HowItWorks_ProfileSettings {
            get {
                return ResourceManager.GetString("GeneralTextFormat_HowItWorks_ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find path to Innkeeper &quot;{0}&quot;—finding another.
        /// </summary>
        internal static string GeneralTextFormat_InnkeeperNotNavigable {
            get {
                return ResourceManager.GetString("GeneralTextFormat_InnkeeperNotNavigable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innkeeper &quot;{0}&quot; is not present—finding another..
        /// </summary>
        internal static string GeneralTextFormat_InnkeeperNotPresent {
            get {
                return ResourceManager.GetString("GeneralTextFormat_InnkeeperNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the disposition of {0} items..
        /// </summary>
        internal static string GeneralTextFormat_ItemDisposition_ToolTip {
            get {
                return ResourceManager.GetString("GeneralTextFormat_ItemDisposition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mail {0}&quot;.
        /// </summary>
        internal static string GeneralTextFormat_MailItem_Label {
            get {
                return ResourceManager.GetString("GeneralTextFormat_MailItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, {1} items will be mailed if:{0}* The {1} item is &apos;unbound&apos;, and{0}* A Mail Recipient has been configured..
        /// </summary>
        internal static string GeneralTextFormat_MailItem_ToolTip {
            get {
                return ResourceManager.GetString("GeneralTextFormat_MailItem_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimizing {0}.
        /// </summary>
        internal static string GeneralTextFormat_MinimizingBuddyBot {
            get {
                return ResourceManager.GetString("GeneralTextFormat_MinimizingBuddyBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to {0}  (dist: {1}) @ {2}.
        /// </summary>
        internal static string GeneralTextFormat_MovingToPlace {
            get {
                return ResourceManager.GetString("GeneralTextFormat_MovingToPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay is not active, or Desktop Composition is disabled in your operating system.{0}    The {1} will not be available because of this..
        /// </summary>
        internal static string GeneralTextFormat_OverlayIsNotActive {
            get {
                return ResourceManager.GetString("GeneralTextFormat_OverlayIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile loading{0}(please wait).
        /// </summary>
        internal static string GeneralTextFormat_ProfileLoadingPleaseWait {
            get {
                return ResourceManager.GetString("GeneralTextFormat_ProfileLoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring {0}.
        /// </summary>
        internal static string GeneralTextFormat_RestoringBuddyBot {
            get {
                return ResourceManager.GetString("GeneralTextFormat_RestoringBuddyBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sell {0}&quot;.
        /// </summary>
        internal static string GeneralTextFormat_SellItem_Label {
            get {
                return ResourceManager.GetString("GeneralTextFormat_SellItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, {1} items will be sold to a vendor if:{0}* The item is not on the &apos;protected items&apos; list, and{0}* The item is soulbound, or{0}* {1} item mailing is disabled.
        /// </summary>
        internal static string GeneralTextFormat_SellItem_ToolTip {
            get {
                return ResourceManager.GetString("GeneralTextFormat_SellItem_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin can only be enabled or disabled from the main {0} UI..
        /// </summary>
        internal static string GeneralTextFormat_ThisPluginCanOnlyBeEnabledOrDisabledFromTheMainHonorbuddyUI {
            get {
                return ResourceManager.GetString("GeneralTextFormat_ThisPluginCanOnlyBeEnabledOrDisabledFromTheMainHonorbuddyUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate an Innkeeper on Map {0}({1}) to pursue..
        /// </summary>
        internal static string GeneralTextFormat_UnableToLocateInnkeeperOnMap {
            get {
                return ResourceManager.GetString("GeneralTextFormat_UnableToLocateInnkeeperOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor actions cancelled: {0}.
        /// </summary>
        internal static string GeneralTextFormat_VendorActionsCancelled {
            get {
                return ResourceManager.GetString("GeneralTextFormat_VendorActionsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor actions scheduled: {0}.
        /// </summary>
        internal static string GeneralTextFormat_VendorActionsScheduled {
            get {
                return ResourceManager.GetString("GeneralTextFormat_VendorActionsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Configuration....
        /// </summary>
        internal static string Item_BotConfiguration_Label {
            get {
                return ResourceManager.GetString("Item_BotConfiguration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings for the currently selected Bot..
        /// </summary>
        internal static string Item_BotConfiguration_ToolTip {
            get {
                return ResourceManager.GetString("Item_BotConfiguration_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot ({0}) configuration....
        /// </summary>
        internal static string Item_BotConfigurationSpecific_LabelFormat {
            get {
                return ResourceManager.GetString("Item_BotConfigurationSpecific_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings for the &apos;{0}&apos; bot..
        /// </summary>
        internal static string Item_BotConfigurationSpecific_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_BotConfigurationSpecific_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot &apos;{0}&apos; does not have any configuration..
        /// </summary>
        internal static string Item_BotConfigurationSpecificUnavailable_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_BotConfigurationSpecificUnavailable_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot does not have any configuration..
        /// </summary>
        internal static string Item_BotConfigurationUnavailable_ToolTip {
            get {
                return ResourceManager.GetString("Item_BotConfigurationUnavailable_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots.
        /// </summary>
        internal static string Item_Bots_Label {
            get {
                return ResourceManager.GetString("Item_Bots_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the current bot for use by {0}..
        /// </summary>
        internal static string Item_Bots_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_Bots_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings &amp; Tools....
        /// </summary>
        internal static string Item_BuddyBotConfiguration_LabelFormat {
            get {
                return ResourceManager.GetString("Item_BuddyBotConfiguration_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main configuration settings for {0}..
        /// </summary>
        internal static string Item_BuddyBotConfiguration_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_BuddyBotConfiguration_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        internal static string Item_BuddyControlPanelPreferences_Label {
            get {
                return ResourceManager.GetString("Item_BuddyControlPanelPreferences_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings for the {0}..
        /// </summary>
        internal static string Item_BuddyControlPanelPreferences_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_BuddyControlPanelPreferences_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Routine ({0}) configuration....
        /// </summary>
        internal static string Item_CombatRoutineConfiguration_LabelFormat {
            get {
                return ResourceManager.GetString("Item_CombatRoutineConfiguration_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings for the {0} Combat Routine..
        /// </summary>
        internal static string Item_CombatRoutineConfiguration_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_CombatRoutineConfiguration_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Item_ContextMenuCancel_Label {
            get {
                return ResourceManager.GetString("Item_ContextMenuCancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the context menu with no action..
        /// </summary>
        internal static string Item_ContextMenuCancel_ToolTip {
            get {
                return ResourceManager.GetString("Item_ContextMenuCancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Bar Size:.
        /// </summary>
        internal static string Item_ControlBarSize_Label {
            get {
                return ResourceManager.GetString("Item_ControlBarSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alters the size of the controls in the Control Bar panel..
        /// </summary>
        internal static string Item_ControlBarSize_ToolTip {
            get {
                return ResourceManager.GetString("Item_ControlBarSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools....
        /// </summary>
        internal static string Item_DeveloperTools_Label {
            get {
                return ResourceManager.GetString("Item_DeveloperTools_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Developer Tools panel..
        /// </summary>
        internal static string Item_DeveloperTools_ToolTip {
            get {
                return ResourceManager.GetString("Item_DeveloperTools_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Item_Exit_Label {
            get {
                return ResourceManager.GetString("Item_Exit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuts down {0}..
        /// </summary>
        internal static string Item_Exit_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_Exit_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal:.
        /// </summary>
        internal static string Item_Goal_Label {
            get {
                return ResourceManager.GetString("Item_Goal_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy Authentication Portal.
        /// </summary>
        internal static string Item_Help_BuddyAuthenticationPortal_Label {
            get {
                return ResourceManager.GetString("Item_Help_BuddyAuthenticationPortal_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://buddyauth.com/.
        /// </summary>
        internal static string Item_Help_BuddyAuthenticationPortal_Uri {
            get {
                return ResourceManager.GetString("Item_Help_BuddyAuthenticationPortal_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy Store.
        /// </summary>
        internal static string Item_Help_BuddyStore_Label {
            get {
                return ResourceManager.GetString("Item_Help_BuddyStore_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://store.buddyauth.com/.
        /// </summary>
        internal static string Item_Help_BuddyStore_Uri {
            get {
                return ResourceManager.GetString("Item_Help_BuddyStore_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guides forum.
        /// </summary>
        internal static string Item_Help_GuidesForum_Label {
            get {
                return ResourceManager.GetString("Item_Help_GuidesForum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.thebuddyforum.com/honorbuddy-forum/honorbuddy-guides/.
        /// </summary>
        internal static string Item_Help_GuidesForum_Uri {
            get {
                return ResourceManager.GetString("Item_Help_GuidesForum_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpDesk.
        /// </summary>
        internal static string Item_Help_HelpDesk_Label {
            get {
                return ResourceManager.GetString("Item_Help_HelpDesk_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.thebuddyforum.com/index.php?title=Category:Honorbuddy:HelpDesk.
        /// </summary>
        internal static string Item_Help_HelpDesk_Uri {
            get {
                return ResourceManager.GetString("Item_Help_HelpDesk_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release forum.
        /// </summary>
        internal static string Item_Help_ReleaseForum_Label {
            get {
                return ResourceManager.GetString("Item_Help_ReleaseForum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.thebuddyforum.com/releases/.
        /// </summary>
        internal static string Item_Help_ReleaseForum_Uri {
            get {
                return ResourceManager.GetString("Item_Help_ReleaseForum_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        internal static string Item_Help_ReleaseNotes_Label {
            get {
                return ResourceManager.GetString("Item_Help_ReleaseNotes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://updates.buddyauth.com/GetNewestChangelog?filter=Honorbuddy.
        /// </summary>
        internal static string Item_Help_ReleaseNotes_Uri {
            get {
                return ResourceManager.GetString("Item_Help_ReleaseNotes_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START HERE.
        /// </summary>
        internal static string Item_Help_StartHere_Label {
            get {
                return ResourceManager.GetString("Item_Help_StartHere_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;file:///{APPDIR}/START HERE.html&quot;.
        /// </summary>
        internal static string Item_Help_StartHere_Uri {
            get {
                return ResourceManager.GetString("Item_Help_StartHere_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support forum.
        /// </summary>
        internal static string Item_Help_SupportForum_Label {
            get {
                return ResourceManager.GetString("Item_Help_SupportForum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.thebuddyforum.com/honorbuddy-forum/honorbuddy-support/.
        /// </summary>
        internal static string Item_Help_SupportForum_Uri {
            get {
                return ResourceManager.GetString("Item_Help_SupportForum_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Buddy Forums.
        /// </summary>
        internal static string Item_Help_TheBuddyForums_Label {
            get {
                return ResourceManager.GetString("Item_Help_TheBuddyForums_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thebuddyforum.com/.
        /// </summary>
        internal static string Item_Help_TheBuddyForums_Uri {
            get {
                return ResourceManager.GetString("Item_Help_TheBuddyForums_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Item_Help_Updates_Label {
            get {
                return ResourceManager.GetString("Item_Help_Updates_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://updates.buddyauth.com/.
        /// </summary>
        internal static string Item_Help_Updates_Uri {
            get {
                return ResourceManager.GetString("Item_Help_Updates_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        internal static string Item_Help_Wiki_Label {
            get {
                return ResourceManager.GetString("Item_Help_Wiki_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.thebuddyforum.com/index.php?title=Category:Honorbuddy.
        /// </summary>
        internal static string Item_Help_Wiki_Uri {
            get {
                return ResourceManager.GetString("Item_Help_Wiki_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pursue all quests.
        /// </summary>
        internal static string Item_IgnoreCheckpoints_Label {
            get {
                return ResourceManager.GetString("Item_IgnoreCheckpoints_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Blue.
        /// </summary>
        internal static string Item_ItemAction_MailBlue {
            get {
                return ResourceManager.GetString("Item_ItemAction_MailBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Green.
        /// </summary>
        internal static string Item_ItemAction_MailGreen {
            get {
                return ResourceManager.GetString("Item_ItemAction_MailGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Grey.
        /// </summary>
        internal static string Item_ItemAction_MailGrey {
            get {
                return ResourceManager.GetString("Item_ItemAction_MailGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Purple.
        /// </summary>
        internal static string Item_ItemAction_MailPurple {
            get {
                return ResourceManager.GetString("Item_ItemAction_MailPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail White.
        /// </summary>
        internal static string Item_ItemAction_MailWhite {
            get {
                return ResourceManager.GetString("Item_ItemAction_MailWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Blue.
        /// </summary>
        internal static string Item_ItemAction_SellBlue {
            get {
                return ResourceManager.GetString("Item_ItemAction_SellBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Grey.
        /// </summary>
        internal static string Item_ItemAction_SellGrey {
            get {
                return ResourceManager.GetString("Item_ItemAction_SellGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Purple.
        /// </summary>
        internal static string Item_ItemAction_SellPurple {
            get {
                return ResourceManager.GetString("Item_ItemAction_SellPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell White.
        /// </summary>
        internal static string Item_ItemAction_SellWhite {
            get {
                return ResourceManager.GetString("Item_ItemAction_SellWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Green.
        /// </summary>
        internal static string Item_ItemActon_SellGreen {
            get {
                return ResourceManager.GetString("Item_ItemActon_SellGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Item_ItemQuality_Common {
            get {
                return ResourceManager.GetString("Item_ItemQuality_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string Item_ItemQuality_CommonColor {
            get {
                return ResourceManager.GetString("Item_ItemQuality_CommonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic.
        /// </summary>
        internal static string Item_ItemQuality_Epic {
            get {
                return ResourceManager.GetString("Item_ItemQuality_Epic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Item_ItemQuality_EpicColor {
            get {
                return ResourceManager.GetString("Item_ItemQuality_EpicColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string Item_ItemQuality_Poor {
            get {
                return ResourceManager.GetString("Item_ItemQuality_Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string Item_ItemQuality_PoorColor {
            get {
                return ResourceManager.GetString("Item_ItemQuality_PoorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Item_ItemQuality_Rare {
            get {
                return ResourceManager.GetString("Item_ItemQuality_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Item_ItemQuality_RareColor {
            get {
                return ResourceManager.GetString("Item_ItemQuality_RareColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string Item_ItemQuality_Uncommon {
            get {
                return ResourceManager.GetString("Item_ItemQuality_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Item_ItemQuality_UncommonColor {
            get {
                return ResourceManager.GetString("Item_ItemQuality_UncommonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This keybind will only work when the game client window has focus.{0}Not all keybind combinations will work on a given machine..
        /// </summary>
        internal static string Item_KeybindDisclaimer_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_KeybindDisclaimer_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        internal static string Item_KeybindKey_Label {
            get {
                return ResourceManager.GetString("Item_KeybindKey_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers:.
        /// </summary>
        internal static string Item_KeybindModifiers_Label {
            get {
                return ResourceManager.GetString("Item_KeybindModifiers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybind Pause/Resume:.
        /// </summary>
        internal static string Item_KeybindPauseResume_Label {
            get {
                return ResourceManager.GetString("Item_KeybindPauseResume_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the hotkey for pausing or resuming the bot..
        /// </summary>
        internal static string Item_KeybindPauseResume_ToolTip {
            get {
                return ResourceManager.GetString("Item_KeybindPauseResume_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybind Start/Stop:.
        /// </summary>
        internal static string Item_KeybindStartStop_Label {
            get {
                return ResourceManager.GetString("Item_KeybindStartStop_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the hotkey for starting or stopping the bot..
        /// </summary>
        internal static string Item_KeybindStartStop_ToolTip {
            get {
                return ResourceManager.GetString("Item_KeybindStartStop_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Profile.
        /// </summary>
        internal static string Item_LoadProfile_Label {
            get {
                return ResourceManager.GetString("Item_LoadProfile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Buddy Store....
        /// </summary>
        internal static string Item_LoadProfileFromBuddyStore_Label {
            get {
                return ResourceManager.GetString("Item_LoadProfileFromBuddyStore_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use main Honorbuddy window for this.
        /// </summary>
        internal static string Item_LoadProfileFromBuddyStoreExcuse_Label {
            get {
                return ResourceManager.GetString("Item_LoadProfileFromBuddyStoreExcuse_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From File....
        /// </summary>
        internal static string Item_LoadProfileFromFile_Label {
            get {
                return ResourceManager.GetString("Item_LoadProfileFromFile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Web Source....
        /// </summary>
        internal static string Item_LoadProfileFromWebSource_Label {
            get {
                return ResourceManager.GetString("Item_LoadProfileFromWebSource_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Control Positions.
        /// </summary>
        internal static string Item_LockControlPositions_Label {
            get {
                return ResourceManager.GetString("Item_LockControlPositions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, prevents dragging and resizing of the Buddy Control Panel components..
        /// </summary>
        internal static string Item_LockControlPositions_ToolTip {
            get {
                return ResourceManager.GetString("Item_LockControlPositions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Item_Plugins_Label {
            get {
                return ResourceManager.GetString("Item_Plugins_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to enabling and configuring {0} plugins..
        /// </summary>
        internal static string Item_Plugins_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_Plugins_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Configuration....
        /// </summary>
        internal static string Item_ProfileConfiguration_Label {
            get {
                return ResourceManager.GetString("Item_ProfileConfiguration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the user to override certain profile settings..
        /// </summary>
        internal static string Item_ProfileConfiguration_ToolTip {
            get {
                return ResourceManager.GetString("Item_ProfileConfiguration_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        internal static string Item_ProfileLocation_LabelFormat {
            get {
                return ResourceManager.GetString("Item_ProfileLocation_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile location: {0}..
        /// </summary>
        internal static string Item_ProfileLocation_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_ProfileLocation_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads profile: &apos;{0}&apos;..
        /// </summary>
        internal static string Item_RecentProfile_ToolTipFormat {
            get {
                return ResourceManager.GetString("Item_RecentProfile_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Item_Status_Label {
            get {
                return ResourceManager.GetString("Item_Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Display Font Size:.
        /// </summary>
        internal static string Item_StatusDisplayFontSize_Label {
            get {
                return ResourceManager.GetString("Item_StatusDisplayFontSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alters the font size used in the Status Display panel..
        /// </summary>
        internal static string Item_StatusDisplayFontSize_ToolTip {
            get {
                return ResourceManager.GetString("Item_StatusDisplayFontSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI:.
        /// </summary>
        internal static string Item_Uri_Label {
            get {
                return ResourceManager.GetString("Item_Uri_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Item_VendorAction_Mail_Label {
            get {
                return ResourceManager.GetString("Item_VendorAction_Mail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules a visit to the nearest Mailbox..
        /// </summary>
        internal static string Item_VendorAction_Mail_ToolTip {
            get {
                return ResourceManager.GetString("Item_VendorAction_Mail_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail, Repair, &amp; Sell.
        /// </summary>
        internal static string Item_VendorAction_MailSellRepair_Label {
            get {
                return ResourceManager.GetString("Item_VendorAction_MailSellRepair_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules mailing, repairing, and selling activities..
        /// </summary>
        internal static string Item_VendorAction_MailSellRepair_ToolTip {
            get {
                return ResourceManager.GetString("Item_VendorAction_MailSellRepair_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string Item_VendorAction_Repair_Label {
            get {
                return ResourceManager.GetString("Item_VendorAction_Repair_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules a visit to the nearest Repair vendor..
        /// </summary>
        internal static string Item_VendorAction_Repair_ToolTip {
            get {
                return ResourceManager.GetString("Item_VendorAction_Repair_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string Item_VendorAction_Sell_Label {
            get {
                return ResourceManager.GetString("Item_VendorAction_Sell_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules a visit to Sell items at nearest Vendor..
        /// </summary>
        internal static string Item_VendorAction_Sell_ToolTip {
            get {
                return ResourceManager.GetString("Item_VendorAction_Sell_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuddyControlPanel.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string Title_Changelog {
            get {
                return ResourceManager.GetString("Title_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Confirmation.
        /// </summary>
        internal static string Title_ExitConfirmation {
            get {
                return ResourceManager.GetString("Title_ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Keybind.
        /// </summary>
        internal static string Title_InvalidKeybind {
            get {
                return ResourceManager.GetString("Title_InvalidKeybind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Management.
        /// </summary>
        internal static string Title_InventoryManagement {
            get {
                return ResourceManager.GetString("Title_InventoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinding Configuration.
        /// </summary>
        internal static string Title_KeyBindingConfiguration {
            get {
                return ResourceManager.GetString("Title_KeyBindingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string Title_Legal {
            get {
                return ResourceManager.GetString("Title_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a Profile.
        /// </summary>
        internal static string Title_LoadAProfile {
            get {
                return ResourceManager.GetString("Title_LoadAProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a Profile from the Web.
        /// </summary>
        internal static string Title_LoadAProfileFromTheWeb {
            get {
                return ResourceManager.GetString("Title_LoadAProfileFromTheWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Configuration.
        /// </summary>
        internal static string Title_OverlayConfiguration {
            get {
                return ResourceManager.GetString("Title_OverlayConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Configuration Settings.
        /// </summary>
        internal static string Title_ProfileConfigurationSettings {
            get {
                return ResourceManager.GetString("Title_ProfileConfigurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest-specific configuration.
        /// </summary>
        internal static string Title_QuestSpecificConfiguration {
            get {
                return ResourceManager.GetString("Title_QuestSpecificConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string TitleFormat_About {
            get {
                return ResourceManager.GetString("TitleFormat_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Preferences.
        /// </summary>
        internal static string TitleFormat_Preferences {
            get {
                return ResourceManager.GetString("TitleFormat_Preferences", resourceCulture);
            }
        }
    }
}
